namespace Gamegato.SpelunkIO.Connector
{
    public enum MonsterEntry : int
    {
        Snake = 0,
        Cobra = 1,
        Bat = 2,
        Spider = 3,
        SpinnerSpider = 4,
        GiantSpider = 5,
        Skeleton = 6,
        Scorpion = 7,
        Caveman = 8,
        Damsel = 9,
        Shopkeeper = 10,
        TheTunnelMan = 11,
        Scarab = 12,
        TikiMan = 13,
        Frog = 14,
        FireFrog = 15,
        GiantFrog = 16,
        ManTrap = 17,
        Piranha = 18,
        OldBitey = 19,
        KillerBee = 20,
        QueenBee = 21,
        Snail = 22,
        Monkey = 23,
        GoldenMonkey = 24,
        JiangShi = 25,
        GreenKnight = 26,
        BlackKnight = 27,
        Vampire = 28,
        TheGhost = 29,
        Bacterium = 30,
        WormEgg = 31,
        WormBaby = 32,
        Yeti = 33,
        YetiKing = 34,
        Mammoth = 35,
        Alien = 36,
        Ufo = 37,
        AlienTank = 38,
        AlienLord = 39,
        AlienQueen = 40,
        HawkMan = 41,
        CrocMan = 42,
        MagmaMan = 43,
        ScorpionFly = 44,
        Mummy = 45,
        Anubis = 46,
        AnubisIi = 47,
        Olmec = 48,
        Vlad = 49,
        Imp = 50,
        Devil = 51,
        Succubus = 52,
        HorseHead = 53,
        OxFace = 54,
        KingYama = 55
    }
}
